PTS-eUniversity/PTS-eUniversity/Controllers/EndorsementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace PTS_eUniversity.Controllers
{
    public class EndorsementsController : Controller
    {
        public ActionResult Index()
        {
            var identity = User.Identity as ClaimsIdentity;
            var email = identity.FindFirst(ClaimTypes.Email).Value;

            var endorsements = GetEndorsements(email);
            return View(endorsements);
        }

        private Dictionary<string, bool> GetEndorsements(string email)
        {
            var db = new UniversityDbContext();
            Dictionary<string, bool> endorsements = new Dictionary<string, bool>();

            var user = db.Users.Where(x => x.Email == email).FirstOrDefault();
            if (user != null)
            {
                var subjects = db.Subjects.Where(x => x.FacultyId == user.FacultyId);
                var _endorsements = db.Endorsements.Where(x => x.User.Email == email);

                foreach (var subject in subjects)
                {
                    endorsements[subject.Name] = _endorsements.Any(x => x.SubjectId == subject.Id);
                }
            }

            return endorsements;
        }
    }
}

PTS-eUniversity/PTS-eUniversity/Controllers/GradesController.cs
using System.Linq;
using System.Security.Claims;
using System.Web.Mvc;

namespace PTS_eUniversity.Controllers
{
    public class GradesController : Controller
    {
        public ActionResult Index()
        {
            var db = new UniversityDbContext();
            var identity = User.Identity as ClaimsIdentity;
            var email = identity.FindFirst(ClaimTypes.Email).Value;

            var grades = db.Grades.Where(x => x.User.Email == email).ToList();
            return View(grades);
        }
    }
}

PTS-eUniversity/PTS-eUniversity/Controllers/InsurancesController.cs
using System.Linq;
using System.Security.Claims;
using System.Web.Mvc;

namespace PTS_eUniversity.Controllers
{
    public class InsurancesController : Controller
    {
        public ActionResult Index()
        {
            var db = new UniversityDbContext();
            var identity = User.Identity as ClaimsIdentity;
            var email = identity.FindFirst(ClaimTypes.Email).Value;

            var insurances = db.Insurances.Where(x => x.User.Email == email).ToList();
            return View(insurances);
        }
    }
}

PTS-eUniversity/PTS-eUniversity/Controllers/ProfileController.cs
using System.Security.Claims;
using System.Web.Mvc;
using System.Linq;

namespace PTS_eUniversity.Controllers
{
    public class ProfileController : Controller
    {
        public ActionResult Index()
        {
            var db = new UniversityDbContext();
            var identity = User.Identity as ClaimsIdentity;
            var email = identity.FindFirst(ClaimTypes.Email).Value;

            var user = db.Users.Where(x => x.Email == email).FirstOrDefault();
            return View(user);
        }
    }
}

PTS-eUniversity/PTS-eUniversity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - е-Университет</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("е-Университет", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @if (User.Identity.IsAuthenticated)
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Оценки", "Index", "Grades", null, new { area = "" })</li>
                        <li>@Html.ActionLink("Заверки", "Index", "Endorsements", null, new { area = "" })</li>
                        <li>@Html.ActionLink("Осигуровки", "Index", "Insurances", null, new { area = "" })</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Профил", "Index", "Profile", null, new { area = "" })</li>
                        <li>@Html.ActionLink("Изход", "LogOut", "Auth", null, new { area = "" })</li>
                    </ul>
                </div>
            }
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - е-Университет</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>